### Dataset

In [1]:
import pandas as pd
from auto_ts import auto_timeseries
import dill
import talib
import numpy as np
import warnings

warnings.filterwarnings('ignore')

from sklearn.model_selection import TimeSeriesSplit
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization
from keras.regularizers import l2
from keras.optimizers import Adam, RMSprop, SGD
from scikeras.wrappers import KerasRegressor
from keras.callbacks import EarlyStopping
from skopt import BayesSearchCV
from sklearn.preprocessing import LabelEncoder
import tensorflow.keras.backend as K
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder
from keras.losses import categorical_crossentropy
from sklearn.metrics import log_loss
from keras.utils import to_categorical

Imported auto_timeseries version:0.0.90. Call by using:
model = auto_timeseries(score_type='rmse',
        time_interval='M', non_seasonal_pdq=None, seasonality=False,
        seasonal_period=12, model_type=['best'], verbose=2, dask_xgboost_flag=0)
model.fit(traindata, ts_column,target)
model.predict(testdata, model='best')



2024-05-13 09:01:18.822521: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# Evito que ciertas columnas se transformen a notacion cientifica en las predicciones
pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.max_columns', None)

In [3]:
columns = [
    'Open_time',
    'Open',
    'High',
    'Low',
    # 'Close',
    'Number of trades',
    'Close_BTCUSDT',
    'Volume_BTCUSDT',
    'Number_of_trades_BTCUSDT',
    'Close_ETHUSDT',
    'Volume_ETHUSDT',
    'Number_of_trades_ETHUSDT',
    'Close_BNBUSDT',
    'Volume_BNBUSDT',
    'Number_of_trades_BNBUSDT',
    'SMA_20',
    'EMA_20',
    'Upper_Band',
    'Middle_Band',
    'Lower_Band',
    'RSI',
    'buy_1000x_high_coinbase',
    'sell_1000x_high_coinbase',
    'total_trades_coinbase',	
    'Tweets_Utilizados',
    'Tweets_Utilizados_coin',
    'Tweets_Utilizados_referentes',
    'Tweets_Utilizados_whale_alert',
    'Buy_1000x_high',
    'sell_1000x_high',
    'total_trades_binance'
]

### Armado y entrenamiento de un clasificador a partir de los datos originales

#### Modelo convolucional

In [19]:
complete_dataset = pd.read_csv('/Users/mmarchetta/Desktop/Tesis-2024/data-visualization/final_dataset.csv') 
classifier_dataset = complete_dataset[columns]
classifier_dataset['Open_time'] = pd.to_datetime(classifier_dataset['Open_time'])
classifier_dataset['Tendencia'] = complete_dataset['Tendencia']

clasifier_validation = classifier_dataset[-10:]
classifier_dataset = classifier_dataset[:-10]

In [24]:
display(classifier_dataset.tail())

Open_time  Open  High  Low  Number of trades  Close_BTCUSDT  \
941 2024-04-25  6.93  7.00 6.70          71088.00       64498.34   
942 2024-04-26  6.86  6.95 6.71          67383.00       63770.01   
943 2024-04-27  6.76  6.87 6.51          64779.00       63461.98   
944 2024-04-28  6.81  6.95 6.69          43208.00       63118.62   
945 2024-04-29  6.73  6.83 6.47          63006.00       63866.00   

     Volume_BTCUSDT  Number_of_trades_BTCUSDT  Close_ETHUSDT  Volume_ETHUSDT  \
941        31341.46                1375324.00        3155.80       352288.55   
942        27085.19                1025561.00        3131.30       252522.65   
943        20933.06                 912422.00        3255.56       323811.19   
944        16949.20                 790652.00        3263.45       304766.01   
945        28150.23                1152296.00        3216.73       421831.29   

     Number_of_trades_ETHUSDT  Close_BNBUSDT  Volume_BNBUSDT  \
941                 861077.00         613.20       453745.52   
942                 628635.00         598.00       302119.88   
943                 734026.00         596.20       268783.91   
944                 753239.00         600.20       258059.43   
945                 943719.00         592.80       330474.01   

     Number_of_trades_BNBUSDT  SMA_20  EMA_20  Upper_Band  Middle_Band  \
941                 353114.00    7.43    7.45        9.08         7.43   
942                 269508.00    7.34    7.38        8.94         7.34   
943                 233820.00    7.24    7.33        8.73         7.24   
944                 206703.00    7.13    7.27        8.38         7.13   
945                 271926.00    7.03    7.20        8.08         7.03   

     Lower_Band   RSI  buy_1000x_high_coinbase  sell_1000x_high_coinbase  \
941        5.77 38.83                    21.00                     26.00   
942        5.74 37.81                    29.00                     24.00   
943        5.76 38.57                    17.00                     17.00   
944        5.88 37.66                    16.00                     20.00   
945        5.97 36.02                    69.00                     37.00   

     total_trades_coinbase  Tweets_Utilizados  Tweets_Utilizados_coin  \
941               33468.00                151                     114   
942               26619.00                117                     106   
943               25565.00                101                     138   
944               20954.00                 82                     106   
945               33959.00                115                     125   

     Tweets_Utilizados_referentes  Tweets_Utilizados_whale_alert  \
941                          0.00                          22.00   
942                          0.00                          14.00   
943                          0.00                           7.00   
944                          0.00                          13.00   
945                          0.00                          24.00   

     Buy_1000x_high  sell_1000x_high  total_trades_binance Tendencia  
941          242.00           219.00              48000.00   Lateral  
942          292.00           324.00              42000.00   Lateral  
943          248.00           179.00              41000.00   Lateral  
944          173.00           165.00              26000.00   Lateral  
945          260.00           188.00              41000.00   Bajista

In [25]:
classifier_dataset.shape

(946, 31)

In [26]:
X = classifier_dataset.drop(columns=["Tendencia", "Open_time"])
y = classifier_dataset["Tendencia"]

# label_encoder = LabelEncoder()
# y_encoded = label_encoder.fit_transform(classifier_dataset["Tendencia"])

y = y.to_numpy().reshape(-1, 1)
onehot_encoder = OneHotEncoder(sparse=False)
y_one_hot = onehot_encoder.fit_transform(y)


In [27]:
display(y_one_hot)

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [28]:
# Function to create the model
def create_model(activation, units, dropout, learning_rate, l2_penalty, depth, optimizer='adam'):
    model = Sequential()
    model.add(Conv1D(units, kernel_size=3, activation=activation, input_shape=(len(X.columns), 1)))
    model.add(MaxPooling1D(pool_size=2))
    model.add(BatchNormalization())

    for _ in range(depth - 1):
        model.add(Conv1D(units, kernel_size=3, activation=activation))
        model.add(MaxPooling1D(pool_size=2))
        model.add(BatchNormalization())

    model.add(Flatten())
    model.add(Dense(units, activation=activation, kernel_regularizer=l2(l2_penalty)))
    model.add(Dropout(dropout))
    model.add(BatchNormalization())
    model.add(Dense(units=3, activation='softmax'))

    if optimizer == 'adam':
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        optimizer = RMSprop(learning_rate=learning_rate)
    elif optimizer == 'sgd':
        optimizer = SGD(learning_rate=learning_rate)

    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

regressor = KerasRegressor(build_fn=create_model, verbose=0, activation='relu', units=50, dropout=0.2, learning_rate=0.1, l2_penalty=0.001, depth=2, optimizer='adam')
early_stopping = EarlyStopping(monitor='val_loss', patience=5)

# Define cross-validation
cv = TimeSeriesSplit(n_splits=10).split(X)

# Define parameter space
param_space = {
    'depth': [2, 3],
    'activation': ['relu', 'tanh', 'swish', 'selu'],
    'units': [64, 128, 256, 512],
    'dropout': [0.1, 0.2, 0.3, 0.4],
    'learning_rate': [0.01, 0.001, 0.0001],
    'epochs': [10, 20, 30, 50, 100],
    'batch_size': [32, 64, 128],
    'optimizer': ['adam', 'rmsprop', 'sgd'],
    'l2_penalty': [0.001, 0.01, 0.1]
}

def categorical_crossentropy_loss(estimator, X_test, y_test):
    y_pred = estimator.predict(X_test)
    loss = log_loss(y_test, y_pred)
    return loss

# Perform Bayesian optimization
bayes_search = BayesSearchCV(regressor, param_space, scoring=categorical_crossentropy_loss, cv=cv,verbose=1)
bayes_result = bayes_search.fit(X, y_one_hot, callbacks=[early_stopping])


In [188]:
# Show best results
print("Best score:", bayes_result.best_score_)
print("Best parameters:", bayes_result.best_params_)

# Entrenar el modelo con los mejores hiperparámetros
best_model = bayes_result.best_estimator_
best_model.fit(X, y_one_hot)

Best score: 6.935171386702793
Best parameters: OrderedDict([('activation', 'selu'), ('batch_size', 128), ('depth', 3), ('dropout', 0.3), ('epochs', 10), ('l2_penalty', 0.001), ('learning_rate', 0.01), ('optimizer', 'rmsprop'), ('units', 512)])


KerasRegressor(
	model=None
	build_fn=<function create_model at 0x7fe48cdbad30>
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=128
	validation_batch_size=None
	verbose=0
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=10
	activation=selu
	units=512
	dropout=0.3
	learning_rate=0.01
	l2_penalty=0.001
	depth=3
)

In [189]:
import json

# Obtener los hiperparámetros y puntajes de los 5 mejores modelos
top_n_models = 5
best_params_list = []
best_scores_list = []

for i in range(min(top_n_models, len(bayes_search.cv_results_['params']))):
    best_params_list.append(bayes_search.cv_results_['params'][i])
    best_scores_list.append(bayes_search.cv_results_['mean_test_score'][i])

# Guardar los hiperparámetros de los 5 mejores modelos en un archivo JSON
with open('conv_classifier/top_5_hyperparameters.json', 'w') as f:
    json.dump({'best_params': best_params_list, 'best_scores': best_scores_list}, f)

# O imprimir los hiperparámetros
print("Top 5 mejores modelos:")
for i in range(len(best_params_list)):
    print("Modelo", i+1)
    print("Hiperparámetros:", best_params_list[i])
    print("Puntaje:", best_scores_list[i])


Top 5 mejores modelos:
Modelo 1
Hiperparámetros: OrderedDict([('activation', 'selu'), ('batch_size', 128), ('depth', 2), ('dropout', 0.2), ('epochs', 20), ('l2_penalty', 0.1), ('learning_rate', 0.001), ('optimizer', 'adam'), ('units', 64)])
Puntaje: 1.5275572624457179
Modelo 2
Hiperparámetros: OrderedDict([('activation', 'swish'), ('batch_size', 128), ('depth', 3), ('dropout', 0.2), ('epochs', 100), ('l2_penalty', 0.01), ('learning_rate', 0.01), ('optimizer', 'adam'), ('units', 64)])
Puntaje: 1.5749713206672962
Modelo 3
Hiperparámetros: OrderedDict([('activation', 'swish'), ('batch_size', 64), ('depth', 2), ('dropout', 0.1), ('epochs', 10), ('l2_penalty', 0.1), ('learning_rate', 0.0001), ('optimizer', 'rmsprop'), ('units', 256)])
Puntaje: 1.5119730230325128
Modelo 4
Hiperparámetros: OrderedDict([('activation', 'relu'), ('batch_size', 32), ('depth', 2), ('dropout', 0.3), ('epochs', 100), ('l2_penalty', 0.001), ('learning_rate', 0.001), ('optimizer', 'rmsprop'), ('units', 64)])
Puntaje: 

#### Armado del ensamble

In [29]:
def generate_prime_seeds(n):
    seeds = []
    num = 70001  # Comenzamos desde el primer número primo mayor que 70000
    while len(seeds) < n:
        is_prime = True
        for i in range(2, int(num**0.5) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            seeds.append(num)
        num += 1
    return seeds


In [30]:
## Clase personalizada para hacer el ensamble, dado que sklearn no provee ninguna clase que permita hacer ensmble
## de modelos re regresion multivariados
class MultivariableVotingRegressor:
    def __init__(self, models):
        self.models = models

    def fit(self, X, y):
        for model in self.models:
            model.fit(X, y)

    def predict(self, X):
        # Hacer predicciones con cada modelo
        predictions = np.array([model.predict(X) for model in self.models])
        
        # Calcular la moda de las predicciones
        mode_predictions = np.argmax(np.sum(predictions, axis=0), axis=1)
        
        return mode_predictions


In [31]:

import json

# Leer los hiperparámetros desde el archivo JSON
with open('conv_classifier/top_5_hyperparameters.json', 'r') as f:
    top_hyperparameters = json.load(f)

prime_seeds = generate_prime_seeds(300)
models = []
best_seeds= {}

# Train models with different seeds for each set of hyperparameters
for mode_number, params in enumerate(top_hyperparameters['best_params']):
    best_validation_errors = {}
    
    for seed_number, seed in enumerate(prime_seeds):
        model = KerasRegressor(build_fn=create_model, random_state=seed, verbose=0, **params)
        model.fit(X, y_one_hot)
        
        # Make predictions with the model
        model_predictions = model.predict(X)
        
        # Calculate error (training error)
        train_error = categorical_crossentropy(y_one_hot, model_predictions)
        
        mean_train_error = np.mean(train_error)

        # Update best validation error for this seed
        best_validation_errors[seed] = mean_train_error
    
    # print("Best validation errors:", best_validation_errors)

    # Find the best seed for this set of hyperparameters
    best_seed_for_params = min(best_validation_errors, key=lambda k: best_validation_errors[k])
    best_seeds[str(params)] = best_seed_for_params
    
    # Create and train the model with the best seed
    model = KerasRegressor(build_fn=create_model, random_state=best_seed_for_params, verbose=0, **params)
    model.fit(X, y_one_hot)
    models.append(model)

# Define and train the ensemble model
ensemble = MultivariableVotingRegressor(models)
ensemble.fit(X, y_one_hot)

# Save the best seeds to a JSON file
with open('conv_classifier/best_seeds.json', 'w') as f:
    json.dump(best_seeds, f)


#### Clasificacion con el ensamble sobre las redicciones de los modelos generativos

In [33]:
with open('conv_classifier/best_seeds.json', 'r') as f:
    best_seeds = json.load(f)

# 21 Crear y entrenar los modelos con los hiperparámetros y semillas guardados
models = []
for params_str, seed in best_seeds.items():
    params = json.loads(params_str.replace("'", "\""))
    model = KerasRegressor(build_fn=create_model, random_state=seed, **params)
    model.fit(X, y_one_hot)
    models.append(model)

Epoch 1/20
8/8 [==============================] - 5s 36ms/step - loss: 11.3976 - accuracy: 0.4017
Epoch 2/20
8/8 [==============================] - 0s 40ms/step - loss: 9.7886 - accuracy: 0.3996
Epoch 3/20
8/8 [==============================] - 0s 32ms/step - loss: 8.3017 - accuracy: 0.4440
Epoch 4/20
8/8 [==============================] - 0s 28ms/step - loss: 7.0857 - accuracy: 0.4408
Epoch 5/20
8/8 [==============================] - 0s 30ms/step - loss: 6.0468 - accuracy: 0.4397
Epoch 6/20
8/8 [==============================] - 0s 48ms/step - loss: 5.1923 - accuracy: 0.4524
Epoch 7/20
8/8 [==============================] - 0s 40ms/step - loss: 4.4225 - accuracy: 0.4683
Epoch 8/20
8/8 [==============================] - 0s 29ms/step - loss: 3.8545 - accuracy: 0.4535
Epoch 9/20
8/8 [==============================] - 0s 34ms/step - loss: 3.3517 - accuracy: 0.4556
Epoch 10/20
8/8 [==============================] - 0s 31ms/step - loss: 2.9717 - accuracy: 0.4323
Epoch 11/20
8/8 [===========

In [34]:
ensemble = MultivariableVotingRegressor(models)
ensemble.fit(X, y_one_hot)

Epoch 1/20
8/8 [==============================] - 4s 33ms/step - loss: 11.3976 - accuracy: 0.4017
Epoch 2/20
8/8 [==============================] - 0s 48ms/step - loss: 9.7886 - accuracy: 0.3996
Epoch 3/20
8/8 [==============================] - 0s 45ms/step - loss: 8.3017 - accuracy: 0.4440
Epoch 4/20
8/8 [==============================] - 0s 38ms/step - loss: 7.0857 - accuracy: 0.4408
Epoch 5/20
8/8 [==============================] - 0s 43ms/step - loss: 6.0468 - accuracy: 0.4397
Epoch 6/20
8/8 [==============================] - 0s 34ms/step - loss: 5.1923 - accuracy: 0.4524
Epoch 7/20
8/8 [==============================] - 0s 31ms/step - loss: 4.4225 - accuracy: 0.4683
Epoch 8/20
8/8 [==============================] - 0s 36ms/step - loss: 3.8545 - accuracy: 0.4535
Epoch 9/20
8/8 [==============================] - 0s 29ms/step - loss: 3.3517 - accuracy: 0.4556
Epoch 10/20
8/8 [==============================] - 0s 32ms/step - loss: 2.9717 - accuracy: 0.4323
Epoch 11/20
8/8 [===========

##### Datos originales:

In [36]:
display(clasifier_validation)

Open_time  Open  High  Low  Number of trades  Close_BTCUSDT  \
946 2024-04-30  6.59  6.67 6.04         115512.00       60672.00   
947 2024-05-01  6.42  6.93 6.13         175570.00       58364.97   
948 2024-05-02  6.90  7.41 6.69         109002.00       59060.61   
949 2024-05-03  7.27  7.39 7.00         109634.00       62882.01   
950 2024-05-04  7.24  7.28 7.11          71120.00       63892.04   
951 2024-05-05  7.12  7.40 7.01          72928.00       64012.00   
952 2024-05-06  7.30  7.47 7.06          94264.00       63165.19   
953 2024-05-07  7.12  7.29 6.98          64947.00       62312.08   
954 2024-05-08  6.99  7.19 6.89          75550.00       61193.03   
955 2024-05-09  6.98  7.09 6.78          75016.00       63074.01   

     Volume_BTCUSDT  Number_of_trades_BTCUSDT  Close_ETHUSDT  Volume_ETHUSDT  \
946        54947.66                1985671.00        3014.05       561717.49   
947        81166.47                2401089.00        2972.46       624963.78   
948        47583.82                1572898.00        2986.19       365939.72   
949        43628.40                1558661.00        3102.61       355825.84   
950        24368.69                1113509.00        3117.23       196263.95   
951        18526.75                 992921.00        3136.41       218760.27   
952        34674.92                1392557.00        3062.60       355135.30   
953        25598.79                1272898.00        3005.69       298796.68   
954        26121.19                1415152.00        2974.21       266934.81   
955        30660.81                1381957.00        3036.23       238561.75   

     Number_of_trades_ETHUSDT  Close_BNBUSDT  Volume_BNBUSDT  \
946                1292873.00         578.40       766513.45   
947                1365039.00         561.80       669027.32   
948                 880167.00         560.50       359794.32   
949                 859542.00         587.00       342906.43   
950                 575026.00         585.70       197129.25   
951                 600693.00         592.00       180458.24   
952                 873200.00         588.20       278669.01   
953                 815246.00         576.50       289488.71   
954                 830635.00         588.60       297016.62   
955                 686147.00         596.80       464857.60   

     Number_of_trades_BNBUSDT  SMA_20  EMA_20  Upper_Band  Middle_Band  \
946                 486465.00    6.93    7.13        7.80         6.93   
947                 427425.00    6.85    7.11        7.41         6.85   
948                 250921.00    6.85    7.12        7.42         6.85   
949                 257575.00    6.90    7.14        7.44         6.90   
950                 210303.00    6.91    7.13        7.46         6.91   
951                 180794.00    6.94    7.15        7.51         6.94   
952                 248490.00    6.96    7.15        7.53         6.96   
953                 266127.00    6.98    7.13        7.52         6.98   
954                 249379.00    6.99    7.12        7.52         6.99   
955                 332988.00    7.01    7.11        7.52         7.01   

     Lower_Band   RSI  buy_1000x_high_coinbase  sell_1000x_high_coinbase  \
946        6.05 34.18                    51.00                     55.00   
947        6.29 43.30                    42.00                     50.00   
948        6.29 49.27                    87.00                     57.00   
949        6.35 48.86                    52.00                     40.00   
950        6.36 46.98                    68.00                     50.00   
951        6.37 50.00                    37.00                     52.00   
952        6.39 47.10                    49.00                     71.00   
953        6.44 45.10                    21.00                     25.00   
954        6.46 44.94                    17.00                     24.00   
955        6.50 46.32                    18.00                     17.00   

     total_trades_

In [37]:
n_clases = 3 

validation_predictions = ensemble.predict(clasifier_validation.drop(columns=["Open_time", "Tendencia"]))
predicciones_one_hot = to_categorical(validation_predictions, num_classes=n_clases)
etiquetas_numericas = np.argmax(predicciones_one_hot, axis=1)
categorias_clases = onehot_encoder.categories_[0]
nombres_clases = [categorias_clases[indice] for indice in etiquetas_numericas]

display(validation_predictions)
display(categorias_clases)
display(nombres_clases)

1/1 [==============================] - 0s 292ms/step


array([1, 0, 0, 0, 2, 2, 0, 0, 0, 0])

array(['Alcista', 'Bajista', 'Lateral'], dtype=object)

['Bajista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Lateral',
 'Lateral',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista']

##### Datos generados por auto ml con prophet:

In [38]:
auto_ml_prophet_df = pd.read_csv('auto_timeseries_models_prophet/predicciones.csv')
auto_mp_prophet_predictions = ensemble.predict(auto_ml_prophet_df.drop(columns=["Open_time", "Close"]))

predicciones_one_hot = to_categorical(auto_mp_prophet_predictions, num_classes=n_clases)
etiquetas_numericas = np.argmax(predicciones_one_hot, axis=1)
categorias_clases = onehot_encoder.categories_[0]
nombres_clases = [categorias_clases[indice] for indice in etiquetas_numericas]

display(auto_mp_prophet_predictions)
display(categorias_clases)
display(nombres_clases)

1/1 [==============================] - 0s 36ms/step


array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

array(['Alcista', 'Bajista', 'Lateral'], dtype=object)

['Bajista',
 'Bajista',
 'Bajista',
 'Bajista',
 'Alcista',
 'Alcista',
 'Bajista',
 'Bajista',
 'Bajista',
 'Bajista']

##### Datos generados por auto ml con stats:

In [40]:
auto_ml_stats_df = pd.read_csv('auto_timeseries_models/predicciones.csv')
auto_mp_stats_predictions = ensemble.predict(auto_ml_stats_df.drop(columns=["Open_time", "Close"]))

predicciones_one_hot = to_categorical(auto_mp_stats_predictions, num_classes=n_clases)
etiquetas_numericas = np.argmax(predicciones_one_hot, axis=1)
categorias_clases = onehot_encoder.categories_[0]
nombres_clases = [categorias_clases[indice] for indice in etiquetas_numericas]

display(auto_mp_stats_predictions)
display(categorias_clases)
display(nombres_clases)

1/1 [==============================] - 0s 49ms/step


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array(['Alcista', 'Bajista', 'Lateral'], dtype=object)

['Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista']

##### Datos generados por auto ml con modelos clasicos:

In [39]:
auto_ml_df = pd.read_csv('h2o_models/predicciones.csv')
auto_mp_predictions = ensemble.predict(auto_ml_df.drop(columns=["Open_time", "Next_Day_Target", "Close"]))

predicciones_one_hot = to_categorical(auto_mp_predictions, num_classes=n_clases)
etiquetas_numericas = np.argmax(predicciones_one_hot, axis=1)
categorias_clases = onehot_encoder.categories_[0]
nombres_clases = [categorias_clases[indice] for indice in etiquetas_numericas]

display(auto_mp_predictions)
display(categorias_clases)
display(nombres_clases)

1/1 [==============================] - 0s 43ms/step


array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

array(['Alcista', 'Bajista', 'Lateral'], dtype=object)

['Bajista',
 'Bajista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista',
 'Alcista']